server:
  port: 8080

spring:
  application:
    name: e-regulation

eureka:
  client:
    enabled: false

cassandra:
  contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
  keyspace-name: common
  port: 9042
  username: caclient
  password: 6AH7vbrkMWnfK